<?php

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $article_id
 * @property string $author
 * @property clob $content
 * @property Article $Article
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method integer getArticleId()  Returns the current record's "article_id" value
 * @method string  getAuthor()     Returns the current record's "author" value
 * @method clob    getContent()    Returns the current record's "content" value
 * @method Article getArticle()    Returns the current record's "Article" value
 * @method Comment setId()         Sets the current record's "id" value
 * @method Comment setArticleId()  Sets the current record's "article_id" value
 * @method Comment setAuthor()     Sets the current record's "author" value
 * @method Comment setContent()    Sets the current record's "content" value
 * @method Comment setArticle()    Sets the current record's "Article" value
 * 
 * @package    20130621
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_comment');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('author', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article', array(
             'local' => 'article_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}