<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/07/18 08:15:44

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=blog',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
