<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/06/21 13:47:44

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=weekly_report_beta',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
