<?php

/**
 * ArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Article');
    }
    
    public function getAllOrderedByDate()
    {
    	$q = $this->createQuery('a')
    	->orderBy('a.created_at ASC');
    
    	return $q->execute();
    }
}